[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
nft_candy_machine = "H4AgvHT31RU9GKx3rPtttdhfsb9k6BLGnNR2CkfQvQto"
fair_launch = "faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 test/*.ts"

[workspace]
members = ["nft-candy-machine"]
